fix exception handling of KeyboardInterrupt during startup (#8182)
### Problem

If pants is hit with a <kbd>Ctrl-C</kbd> when in the engine at the right time when it starts up, it fails to handle the exception correctly, due to an incorrect `datatype()` type constraint:
```
Traceback (most recent call last):
  File "/Users/dmcclanahan/tools/pants-v3/src/python/pants/engine/native.py", line 256, in exc_handler
    error_info = native.CFFIExternMethodRuntimeErrorInfo(exc_type, exc_value, traceback)
  File "/Users/dmcclanahan/tools/pants-v3/src/python/pants/util/objects.py", line 229, in __new__
    '\n'.join(type_failure_msgs)))
pants.util.objects.TypedDatatypeInstanceConstructionError: type check error in class CFFIExternMethodRuntimeErrorInfo: 1 error type checking constructor arguments:
field 'exc_value' was invalid: value KeyboardInterrupt('User interrupted execution with control-c!') (with type 'KeyboardInterrupt') must satisfy this type constraint: SubclassesOf(Exception).
```

Additionally, when this occurs, the exception is invisible to the user, because the default behavior decided previously in `exception_sink.py` was to *avoid* printing a stacktrace if errors occurred at import time,:
```
timestamp: 2019-08-17T13:51:45.667543
Exception caught: (pants.build_graph.address_lookup_error.AddressLookupError) (backtrace omitted)
Exception message: Build graph construction failed: RuntimeError cannot use from_handle() on NULL pointer
```

Both of these have led to repeated confusion from users, especially when using pantsd.

### Solution

- Extend the type constraint to be `SubclassesOf(BaseException)`, since apparently `KeyboardInterrupt` is not an `Exception`.
- Default to printing the stacktrace for exceptions during import time instead of hiding it.

### Result

Users don't have mysterious errors when they try to quit a pants run!