Fix the outdir to refer to task workdir
Fix publihs outdir to use _workdir

@Bengy's auto work dir change the workdir for

Verified locally.

Earlier ../pants goal publish src/scala/com/pants/example:jvm-run-example-lib --publish-local=~tdesai/m2/ used to fail.

12:44:56 00:01     [publish]Skipping check for a clean master in test mode.

               FAILURE
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 116, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 81, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/tdesai/projects/pants/.pants.d/publish/jar_create_publish/com.pants-jvm-run-example-lib.jar'
[tw-172-25-20-142 pants]$

=================================
Now

[tw-172-25-20-142 pants]$ PANTS_DEV=1 ./pants goal publish src/scala/com/pants/example:jvm-run-example-lib --publish-local=~tdesai/m2/
*** Running pants in dev mode from /Users/tdesai/projects/pants/src/python/pants/bin/pants_exe.py ***

16:29:26 00:00 [main]
               See a report at: http://localhost:59125/run/pants_run_2014_05_12_16_29_26_234
16:29:26 00:00   [setup]
16:29:26 00:00     [bootstrap]
16:29:26 00:00     [parse]
16:29:26 00:00   [bootstrap]
16:29:26 00:00     [bootstrap-jvm-tools]
16:29:26 00:00   [gen]
16:29:26 00:00     [thrift]
16:29:26 00:00     [scrooge]
16:29:26 00:00     [protoc]
16:29:26 00:00     [antlr]
16:29:26 00:00   [check-exclusives]
16:29:26 00:00     [check-exclusives]
16:29:26 00:00   [resolve]
16:29:26 00:00     [ivy]
16:29:26 00:00   [compile]
16:29:26 00:00     [jvm]
16:29:26 00:00       [scala]
16:29:26 00:00   [resources]
16:29:26 00:00     [prepare]
16:29:26 00:00   [publish]
16:29:26 00:00     [javadoc_publish]
16:29:26 00:00     [scaladoc_publish]
16:29:26 00:00     [jar_create_publish]
16:29:26 00:00     [publish]Skipping check for a clean tdesai/fix_publish in test mode.

               SUCCESS
[tw-172-25-20-142 pants]$

Testing Done:
SO this fixes publishing in dryrun  regression of https://github.com/pantsbuild/pants/commit/1d86550eaa96fafcdd31eda79822caabb7a4329c

CI
https://travis-ci.org/pantsbuild/pants/builds/25022520

Bugs closed: 119

Reviewed at https://rbcommons.com/s/twitter/r/335/