[v2-engine errors] Sort suggestions for typo'd targets, unique them when trace is disabled (#5413)
### Problem

When there are a large number of suggestions, the lack of alphanumeric sorting is frustrating. #4788
### Solution

Sort the suggestions. Additionally, I noticed that because of where this happens, there may be multiple copies of the error message that show up. I changed the default behavior to dedup common errors.

### Result

```
./pants list 3rdparty/python:rutaba --no-print-exception-stacktrace
Exception caught: (<class 'pants.build_graph.address_lookup_error.AddressLookupError'>)

Exception message: "rutaba" was not found in namespace "3rdparty/python". Did you mean one of:
  :Markdown
  :Pygments
  :ansicolors
```

Instead of
```
Exception caught: (<class 'pants.build_graph.address_lookup_error.AddressLookupError'>)

Exception message: Build graph construction failed: ExecutionError Multiple exceptions encountered:
  ResolveError: "rutaba" was not found in namespace "3rdparty/python". Did you mean one of:
  :psutil
  :isort
  :pywatchman
  :pytest-cov
...
  :scandir
  :setuptools
  ResolveError: "rutaba" was not found in namespace "3rdparty/python". Did you mean one of:
  :psutil
  :isort
  :pywatchman
  :pytest-cov
  :setproctitle
...
  :scandir
  :setuptools

```