Repair PyPI user checking in release scripts. (#5787)
PyPI recently switched over to the new "Warehouse" implementation which broke our release scripts that currently rely on HTML parsing.

before:

[omerta pants (master)]$ git rev-parse HEAD; ./build-support/bin/release.sh -o
6a1ac80462820b9746fed311ff868f02e615683b
Owners of pantsbuild.pants:
Traceback (most recent call last):
  File "/Users/kwilson/dev/pants/.pants.d/run/py/CPython-2.7.14/d5e26e10a466d987cfaead3ea238dd3959d1cc92/.bootstrap/_pex/pex.py", line 367, in execute
    self._wrap_coverage(self._wrap_profiling, self._execute)
  File "/Users/kwilson/dev/pants/.pants.d/run/py/CPython-2.7.14/d5e26e10a466d987cfaead3ea238dd3959d1cc92/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
    runner(*args)
  File "/Users/kwilson/dev/pants/.pants.d/run/py/CPython-2.7.14/d5e26e10a466d987cfaead3ea238dd3959d1cc92/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
    runner(*args)
  File "/Users/kwilson/dev/pants/.pants.d/run/py/CPython-2.7.14/d5e26e10a466d987cfaead3ea238dd3959d1cc92/.bootstrap/_pex/pex.py", line 410, in _execute
    return self.execute_entry(self._pex_info.entry_point)
  File "/Users/kwilson/dev/pants/.pants.d/run/py/CPython-2.7.14/d5e26e10a466d987cfaead3ea238dd3959d1cc92/.bootstrap/_pex/pex.py", line 468, in execute_entry
    return runner(entry_point)
  File "/Users/kwilson/dev/pants/.pants.d/run/py/CPython-2.7.14/d5e26e10a466d987cfaead3ea238dd3959d1cc92/.bootstrap/_pex/pex.py", line 473, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/opt/twitter_mde/package/eepython27/2b9f44c3673ea5b18e3c12bf36c35ef93e3d03a547f10d19f45d7097b09a85a1/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/opt/twitter_mde/package/eepython27/2b9f44c3673ea5b18e3c12bf36c35ef93e3d03a547f10d19f45d7097b09a85a1/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/kwilson/dev/pants/.pants.d/pyprep/sources/11e7e1652cb2d9176b129ad84bd11143d8be921b/pants/releases/packages.py", line 132, in <module>
    for owner in sorted(package.owners()):
  File "/Users/kwilson/dev/pants/.pants.d/pyprep/sources/11e7e1652cb2d9176b129ad84bd11143d8be921b/pants/releases/packages.py", line 61, in owners
    raise ValueError("Didn't find package owners in HTML output from {}".format(url))
ValueError: Didn't find package owners in HTML output from https://pypi.python.org/pypi/pantsbuild.pants/1.5.0

FAILURE: /opt/twitter_mde/package/eepython27/2b9f44c3673ea5b18e3c12bf36c35ef93e3d03a547f10d19f45d7097b09a85a1/bin/python2.7 pants.releases.packages list-owners ... exited non-zero (1)


FAILURE
after:

[omerta pants (kwlzn/pypi_user_checking)]$ ./build-support/bin/release.sh -o
Owners of pantsbuild.pants:
benjyw
illicitonion
ity
john.sirois
kwlzn
mateor
stuhood
wisechengyi
...