Revert "Prefix the entire setup.py chroot. (#12359)" (#12370)
This was causing CI to fail with:

> Exception: String("Cannot strip prefix chroot/dist from root directory (Digest with hash Fingerprint<0e3f69284c886c8b9b330122c22ed47e469e2f9020c9938fdf6d15c24471aeae>) - root directory didn't contain a directory named chroot but did contain directory named: dist")

[ci skip-rust]

[ci skip-build-wheels]