fix `cargo install` invocation (#16567)
adds the missing `--version` flag,

fixes seeing (if cargo-ensure-prefix wasn't installed, it too would fail with a much more confusing error)
```
    Updating crates.io index
     Ignored package `cargo-ensure-prefix v0.1.7` is already installed, use --force to override
error: could not find `=0.1.7` in registry `crates-io` with version `*`
     Summary Successfully installed cargo-ensure-prefix! Failed to install =0.1.7 (see error(s) above).
error: some crates failed to install

```
now, looks like:
```
     Ignored package `cargo-ensure-prefix v0.1.7` is already installed, use --force to override
```