Add support for config selectors in dep addresses.
This allows for modelling many variants of a target through a single
target with many configurations.  When the set of applicable
configuratons for a dependee has more than one element, the required
configuration can be specified by "sub-addressing" into a target's
(named) configurations.

This change adds an example of this:
```
./pants run src/python/pants/engine/exp/examples:viz -- \
  tests/python/pants_test/engine/exp/examples/scheduler_inputs \
  compile \
  src/java/codegen/selector:selected
```

As well as an example of what happens when more than one configuration
applies (a failing example):
```
./pants run src/python/pants/engine/exp/examples:viz -- \
  tests/python/pants_test/engine/exp/examples/scheduler_inputs \
  compile \
  src/java/codegen/selector:conflict
...
pants.engine.exp.scheduler.ConflictingProducersError: Collected the
following plans for generating "Sources(u'.java')" from
Target(address=src/thrift/codegen/selector)
  ApacheThriftPlanner
  ScroogePlanner

FAILURE:
/home/jsirois/dev/3rdparty/jsirois-pants3/build-support/pants_dev_deps.venv/bin/python2.7
pants.engine.exp.examples.visualizer:main
tests/python/pants_test/engine/exp/examples/scheduler_inputs compile
src/java/codegen/selector:conflict ... exited non-zero (1)
```

Testing Done:
Locally, ran the `src/java/codegen/selector:selected` case which
yielded the attached plan graph.

CI went green here:
  https://travis-ci.org/pantsbuild/pants/builds/86967611

Bugs closed: 2418, 2439

Reviewed at https://rbcommons.com/s/twitter/r/3025/