Better error message when an address does not exist (#15788)
Part of https://github.com/pantsbuild/pants/issues/14468.

Before:

```
❯ ./pants list src/python/pants/util:fake
ResolveError: 'fake' was not found in namespace 'src/python/pants/util'. Did you mean one of:
  :tests
  :util
```

```
❯ ./pants list src/python/pants/util:fake
  ValueError: The address `3rdparty/python#bad` was not generated by the target `3rdparty/python:python`, which only generated these addresses:

  * 3rdparty/python:python
  * 3rdparty/python#PyYAML
  * 3rdparty/python#ansicolors

Did you mean to use one of those addresses?
```

After:

```
❯ ./pants list src/python/pants/util:fake
ResolveError: The address src/python/pants/util:fake from CLI arguments does not exist.

The target name ':fake' is not defined in the directory src/python/pants/util. Did you mean one of these target names?

  * :tests
  * :util
```

```
❯ ./pants list 3rdparty/python#bad
ResolveError: The address `3rdparty/python#bad` from CLI arguments was not generated by the target `3rdparty/python:python`. Did you mean one of these addresses?

  * 3rdparty/python:python
  * 3rdparty/python#PyYAML
  * 3rdparty/python#ansicolors
 ```

[ci skip-rust]
[ci skip-build-wheels]