fix: missing common targets for node_build_script (#22437)
Summary
--

While the NodeBuildScriptTarget includes
`COMMON_TARGET_FIELDS`(description, tags), the addition of these fields
result in an error -
`TypeError: NodeBuildScript.create() got an unexpected keyword argument
'description'`

Adding both the fields to the NodeBuildScript class