Remove the underlying implementation of `anonymous-telemetry` (#18952)
This is the reason `requests` (and therefore other dependencies) is a
dependency of Pants. This yields a smaller Pants footprint. Lastly, as
Carina [says in
Slack](https://pantsbuild.slack.com/archives/C0D7TNJHL/p1683645016995559?thread_ts=1683644499.629429&cid=C0D7TNJHL):
> We originally expected it would help us provide better tech support,
but it hasn't really panned out for that. If we could substitute in some
other telemetry tool, that could be worthwhile. But given that no major
value being is being returned to the project and it has unfortunately
become a blocker for some users, I think it's time to take humbug out of
people's way one way or another.

After:
```
$ pants package src/python/pants:pants-packaged
$ python -m venv .venv
$ .venv/bin/pip install dist/pantsbuild.pants-2.17.0.dev5-cp38-cp38-linux_x86_64.whl
...
Successfully installed PyYAML-6.0 ansicolors-1.1.8 chevron-0.14.0 fasteners-0.16.3 ijson-3.1.4 importlib-resources-5.0.7 node-semver-0.9.0 packaging-21.3 pantsbuild.pants-2.17.0.dev5 pex-2.1.135 psutil-5.9.0 pyparsing-3.0.9 python-lsp-jsonrpc-1.0.0 setproctitle-1.3.2 setuptools-63.4.3 six-1.16.0 toml-0.10.2 types-PyYAML-6.0.3 types-setuptools-62.6.1 types-toml-0.10.8 typing-extensions-4.3.0 ujson-5.7.0
$ .venv/bin/python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
>>> quit()
```

We're keeping the subsystem in place so that we could swap in another
implementation at a later date.

---------

Co-authored-by: Eric Arellano <14852634+Eric-Arellano@users.noreply.github.com>