[internal] Refactor `AddressSpecs` globs code (#13258)
`AddressGlobSpec` is much simpler and declarative now. It no longer deals with `AddressMap` and `AddressFamily`. Instead, all each spec type does is sets the class property `error_if_no_matches: bool` and the functions `to_build_file_globs()` and `matches(target_resident_dir: str)`.

This refactor allows us to improve our mismatched globs error. Now, we find _all_ mismatched globs, whereas we used to eagerly error on the first one detected. Now:

```
❯ ./pants list src/rust/engine: src/rust/engine/fs:
pants.base.exceptions.ResolveError: No targets found for these address globs: ['src/rust/engine/fs:', 'src/rust/engine:']

Do targets exist in those directories? Maybe run `./pants tailor` to generate BUILD files? See https://www.pantsbuild.org/v2.8/docs/targets about targets and BUILD files.
```

This also applies the same fix from https://github.com/pantsbuild/pants/pull/13252 for the `--tag` filter. It before would not handle that the Target API lets plugin developers subclass the `Tags` field to change it's functionality, e.g. to add defaults. That's fixed by inspecting `Target.get(Tags)`, rather than the `TargetAdaptor` (a light weight wrapper around the BUILD file content).

Outside of that bug fix and new error message, there are no user changes in this. CLI specs behave the same as before.

[ci skip-rust]