Improve error messages for invalid addresses (#15751)
Part of https://github.com/pantsbuild/pants/issues/14468.

File address does not exist:

> ResolveError: The file or directory 'build-support/fake.txt' does not exist on disk in the workspace, so the address 'build-support/fake.txt' from the `files` field from the target //:demo cannot be resolved.

Wildcard used:

> UnsupportedWildcard: The address `dir:` from the `files` field from the target //:demo included a wildcard (`:`), which is not supported.

Absolute path:

> InvalidSpecPath: Invalid address /dir from the `files` field from the target //:demo. Cannot use absolute paths.

Invalid path component:

> InvalidSpecPath: Invalid address `dir/./f.txt` from the `files` field from the target //:demo. It has an un-normalized path part: '/.'.

Invalid parameter:

> InvalidParameters: Invalid address `dir/f.txt@k!=v` from the `files` field from the target //:demo. It has illegal characters in parameter keys: `{'!'}` in `k!=v`.

Missing target name for build root:

> InvalidTargetName: Addresses for generated first-party targets in the build root must include which target generator they come from, such as `pants.toml:original_target`. However, `pants.toml` from the `files` field from the target //:demo did not have a target name.

Generated target, too many `../`:

> Invalid address `build-support/common.sh:../../tgt` from the `files` field from the target //:demo. The target name portion of the address `../../tgt` has too many `../`, which means it refers to a directory above the file path `build-support/common.sh`. Expected no more than 1 instances of `../` in `../../tgt`, but found 2 instances.

Generated target, target is from subdir:

> InvalidTargetName: Invalid address `build-support/common.sh:subdir/tgt` from the `files` field from the target //:demo. The target name portion of the address must refer to a target defined in the same directory or a parent directory of the file path `build-support/common.sh`, but the value `subdir/tgt` is a subdirectory.
 
[ci skip-rust]
[ci skip-build-wheels]