Error out on duplicate artifacts for jar publish.
This adds some extra validation to check_targets to ensure that we
don't have multiple libraries which provide the same artifact.

A nicely formatted error message is output in the event of a
conflict:

    DuplicateArtifactError: Multiple targets define the same artifacts!

      com.example-nail -> internal -> http://example.com
(/private/var/folders/wf/q7mqymv13kq1w7vkzq6y0fr4000258/T/tmpZRPxjZ_BUILD_ROOT/pushdb)
is defined by:
        a:a
        conflict:conflict