Repair `BinaryNotFound` due to `sslv3 alert handshake failure`. (#4853)
Problem

The build recently started failing with SSL errors like:

BinaryNotFound: Failed to fetch binary scripts/cloc/1.66/cloc from any source: (Failed to fetch binary from https://binaries.pantsbuild.org/scripts/cloc/1.66/cloc: Problem GETing data from https://binaries.pantsbuild.org/scripts/cloc/1.66/cloc: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure)
when retrieving artifacts via BinaryUtil.

Solution

Bump the requests version range to permit the latest version (noting no apparent mention of API Changes between current minimal to pypi current based on the changelog here).
Use the requests[security] extra to include a superior/modernized set of underlying SSL libraries (see here for more info).
Bump the cffi version to include a fix for a cryptography build/cffi issue seen here.
Add openssl and libssl-dev to Travis shards to support SSL related builds.
Drop our reliance on the (now 2 versions) old Travis CI image based on observations in #4852, which presumably nets us a transitively better OpenSSL version via apt.
Result

Closes #4852