Allow `@goal_rule`s to request `Targets` and demo with `./v2 binary run` (#9345)
This adds rules to allow rules to request `TargetWithOrigin`, `Targets`, and `TargetsWithOrigins`, then hooks it up to `./v2 binary` and `./v2 run`.

## Result: `./v2 binary run` works with custom target types

So long as those target types have the field `PythonBinarySources` and `EntryPoint` registered, we can now run `./v2 binary` and `./v2 run` on the targets.

## Result: better error messages for invalid target types:

Before:

> ▶ ./v2 --no-print-exception-stacktrace run src/python/pants/util:strutil
>
>
>ERROR: Type PythonTargetAdaptor is not a member of the BinaryTarget @union

After:


> ▶ ./v2 --no-print-exception-stacktrace run src/python/pants/util:strutil
>
>
> ERROR: The `run` and `binary` goals only work with the following target types: ['python_binary']
>
> You used src/python/pants/util:strutil with target type 'python_library'.


This improvement is made possible because of the Target API for two reasons:

1. Field-driven API. Rules now only say what fields they need and ignore all others.
2. We can access all registered target types by requesting the singleton `RegisteredTargetTypes`. 

These two reasons allow us to iterate over every registered BinaryImplementation to determine which target types they work with, i.e. which target types have their required fields. We then flatten this into a single list of valid targets.

This error message works with custom target types, too!

> ▶ ./v2 --no-print-exception-stacktrace run src/python/pants/util:strutil
>
>
> ERROR: The `run` and `binary` goals only work with the following target types: ['custom_python_binary', 'python_binary']
>
> You used src/python/pants/util:strutil with target type 'python_library'.

## Implementation: filtering targets in `@goal_rules`

An `@goal_rule` will typically request `SourcesSnapshots`, `Addresses`, `AddressesWithOrigins`, `Targets`, or `TargetsWithOrigins`. It hasn't yet filtered out which targets it actually cares about. 

The downstream rules, meanwhile will already express which exact fields they need to operate through their rule signature, e.g. `python_create_binary.py` saying it needs `PythonBinaryImplementation` (previously `PythonBinaryFields`). The `@goal_rule` must filter out the relevant targets then pass those fields down to the rule.

--

Here, we use the same pattern used in `fmt.py`, `lint.py`, and `test.py` to do that filtering. 

It no longer makes sense to have a union of target types, like `UnionRule(BinaryTarget, PythonBinary)`. We no longer care about target types, but rather only the required fields for the rule to operate.

Instead, we use `UnionRule(BinaryImplementation, PythonBinaryImplementation)`, where `PythonBinaryImplementation` is a subclass of `BinaryImplementation` that has the methods `is_valid_target()` and `create()`. For any given target, this allows us to check "are there any registered binary implementations that work with this target?" If so, we now have a standardized way of extracting the relevant Fields from that target by calling `implementation.create(target)` and using a union rule to call the appropriate downstream rule.

This is the equivalent of `test.py` having `UnionRule(TestRunner, PytestRunner)`, `lint.py` having `UnionRule(Linter, BanditLinter)`, and `fmt.py` having `UnionRule(Formatter, IsortFormatter)`.