refactor command line target spec resolution and check that all target roots exist (#6480)
### Problem

This should fail regardless of the order of the command-line target specs (the target named `a` does not exist):
```
> ./pants test tests/python/pants_test/option:a
# ...
ResolveError: "a" was not found in namespace "tests/python/pants_test/option". Did you mean one of:
          :options_integration
          :testing
> ./pants test tests/python/pants_test/option:{testing,a}
# ...
 ===== 158 passed, 1 xfailed in 2.77 seconds ======
                     
                   tests/python/pants_test/option:testing                                          .....   SUCCESS
23:25:48 00:12     [junit]
23:25:48 00:12     [go]
23:25:48 00:12     [node]
               Waiting for background workers to finish.
23:25:49 00:13   [complete]
               SUCCESS
```

### Solution

- Move `AddressFamily` and `Address` resolution logic into the `Spec` class and its subclasses instead of doing a massive `if` chain.
- Introduce the `_MappedSpecs` datatype holding the target `Specs`, and the `AddressFamily`s covering the directories indicated by the `Specs`.
- Move all of the address resolution logic into `_MappedSpecs` for clarity, and replace all `if type(obj) is SingleAddress` chains with abstract methods implemented in `Spec` subclasses.
- Add `test_fails_on_nonexistent_specs()` to test the issue described in the Problem section.