Allow a `StringField` to require one of several choices (enum) (#9461)
### Problem

Several times, Fields have wanted to express that they only allow for a fixed number of string values. That is, to act like an Enum.

This pattern has only happened with strings - I've not yet encountered an `IntEnum`-like field, for example.

### Solution

Add a `valid_choices` class property to `StringField`. 

Hook this up to `target-types2`:

![example](https://user-images.githubusercontent.com/14852634/78388448-e291bc00-7595-11ea-89ff-e69569a76c0d.png)

We allow either passing a tuple of strings _or_ an `Enum` instance, which makes for much more flexible call sites.

We always still return back a `str`, rather than a specific `Enum` instance. This makes backward-compatibility much simpler when converting back into a V1 target + makes type hints much simpler.

### Result

Using an invalid value:

> ▶ ./v2 --no-print-exception-stacktrace run build-support/bin:check_banned_imports
>
> ERROR: The 'inherit_path' field in target build-support/bin:check_banned_imports must be one of ['fallback', 'false', 'prefer'], but was 'bad'.

[ci skip-rust-tests]
[ci skip-jvm-tests]