Fix regression in unmatched globs error message (#10595)
Fixes https://github.com/pantsbuild/pants/issues/10574. We were calling `throw(&format("{:?}"))` on an error that was already had type `Failure`, meaning that we were converting a `Failure` to a `String`, then back to a `Failure`, which resulted in an overly chatty error message.

This also fixes error messages involving `DownloadFile`.

Before:
```
 Exception: Throw { val: Unmatched glob from file arguments: "fake", python_traceback: "Traceback (no traceback):\n  <pants native internals>\nException: Unmatched glob from file arguments: \"fake\"", engine_traceback: ["Snapshotting: PathGlobs(globs=(\'fake\',), glob_match_error_behavior=<GlobMatchErrorBehavior.error: \'error\'>, conjunction=<GlobExpansionConjunction.all_match: \'all_match\'>, description_of_origin=\'file arguments\')"] }
```

After:

```
Unmatched glob from file arguments: "fake"
```
  
[ci skip-build-wheels]