Pin `GitPython==3.1.18` by default with Bandit to ensure yanked release isn't used in lockfile generation (#12691)
Poetry does not support yanked releases yet: https://github.com/python-poetry/poetry/issues/2453. As a result, it tries to use GitPython==3.1.20 in the generated lockfile, which results in this error when using Python 3.8+:

```
pex.environment.ResolveError: Failed to resolve requirements from PEX environment @ /private/var/folders/g7/0lj2pw4d6db67tm8m8xj0rc80000gn/T/process-executionpWU6fG/.tmp/tmpafl9tzo5.
Needed macosx_11_0_arm64-cp-39-cp39 compatible dependencies for:
 1: typing-extensions>=3.7.4.3; python_version < "3.10"
    Required by:
      GitPython 3.1.20
    But this pex had no 'typing-extensions' distributions.
```

The workaround is to pin `GitPython` to an un-yanked release.

Also this stops using a setuptools version that works with Python 2 because the default version of Bandit doesn't work with Py2 anymore.


[ci skip-rust]
[ci skip-build-wheels]