Fix V2 isort and Black including the tmpdir in their output (#9683)
Before:

```
▶ ./v2 --changed-since=HEAD lint


would reformat /private/var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/process-executionnVN1WF/tests/python/pants_test/util/test_strutil.py
would reformat /private/var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/process-executionnVN1WF/src/python/pants/util/strutil.py
Oh no! 💥 💔 💥
2 files would be reformatted.

ERROR: /private/var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/process-executionymOGR9/src/python/pants/util/strutil.py Imports are incorrectly sorted.
ERROR: /private/var/folders/sx/pdpbqz4x5cscn9hhfpbsbqvm0000gn/T/process-executionymOGR9/tests/python/pants_test/util/test_strutil.py Imports are incorrectly sorted.
```

After:

```
▶ ./v2 --changed-since=HEAD lint


would reformat tests/python/pants_test/util/test_strutil.py
would reformat src/python/pants/util/strutil.py
Oh no! 💥 💔 💥
2 files would be reformatted.

ERROR: src/python/pants/util/strutil.py Imports are incorrectly sorted.
ERROR: tests/python/pants_test/util/test_strutil.py Imports are incorrectly sorted.
```

Closes https://github.com/pantsbuild/pants/issues/8670.

[ci skip-rust-tests]
[ci skip-jvm-tests]