Improve logging of build-support/isort.sh helper script (#7503)
### Problem
`isort.sh` suffers from two problems:

1. When not using `-f`, the output upon failure is unnecessarily wordy and does not say which files were the actual issue. For example:
```
FAILURE: Exited with return code 1 while running `/Users/eric/.pyenv/shims/python3.6 /Users/eric/.cache/pants/python/CPython-3.6.8/d6bcba436bdefbc27a69dd880d6ee5716e004764/isort-c201e856817dc9ae802d18e3ec45a3bfa4c2ac11.pex --check-only src/python/pants/util/tarutil.py src/python/pants/util/retry.py src/python/pants/util/osutil.py src/python/pants/util/memo.py src/python/pants/util/process_handler.py src/python/pants/util/strutil.py src/python/pants/util/py2_compat.py src/python/pants/util/meta.py src/python/pants/util/xml_parser.py src/python/pants/util/objects.py src/python/pants/util/rwbuf.py src/python/pants/util/collections_abc_backport.py`.

FAILURE
```

2. When using `-f`, we swallow all output. Presumably, the user would like to know which files were changed, rather than having to run `git status` to do this.

### Solution
No longer run the command as `--quiet` and use grep to parse out lines we care about.

### Result
If `--fix` is passed and files were fixed, we will output with return code 0:
```
Fixing /Users/eric/DocsLocal/code/projects/pants/src/python/pants/util/strutil.py
```

If `--fix` is left off, and files had bad sort order, we will output with return code 1:
```
ERROR: /Users/eric/DocsLocal/code/projects/pants/src/python/pants/util/strutil.py Imports are incorrectly sorted.
```