Validate that `pytest-cov` is installed when `[test].use_coverage` is set (#12534)
A user was confused why coverage was not working with this error:

```
ERROR: usage: pex [options] [file_or_dir] [file_or_dir] [...]
pex: error: unrecognized arguments: --cov-report= --cov-config=pyproject.toml --cov
  inifile: None
  rootdir: /tmp/process-executionrPt8j7
```

This is because they overrode `[pytest].pytest_plugins`, so it no longer had `pytest-cov` included. This has been a common source of confusion.

--

We agreed it's better for Pants to eagerly error than to warn to guarantee people see the issue, whereas a warning might be missed in CI logs etc.

[ci skip-rust]