Fix `scalac` plugin paths in BSP options response (#23564)
`handle_bsp_scalac_options_request` put `scalac` plugin jars under
`.pants.d/bsp/`, but emits the `-Xplugin:` options relative to the build
root:

```
-Xplugin:jvm/resolves/scala213/plugins/some-plugin.jar
```

while the jars actually are in
`.pants.d/bsp/jvm/resolves/scala213/plugins`, so there is a mismatch
here which causes BSP to not find the plugin which causes metals to log

```
java.nio.file.NoSuchFileException: /home/alex/code/work/backend/jvm/resolves/scala213/plugins/some-plugin.jar
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$isSupportedPlugin$1(CompilerPlugins.scala:64)
```

This fixes the path to ensure that plugins can be passed to the
presentation compiler.

LLM usage note: Had an LLM write the docs summary for me