Demonstrate use of the Target API with `python_create_binary.py` (#9316)
This adds our very first usage of the Target API in production by using it for `./v2 run` and `./v2 binary`:

```bash
▶ ./v2 run build-support/bin:check_banned_imports


Running target: build-support/bin:check_banned_imports
build-support/bin:check_banned_imports ran successfully.
```

The end functionality is the same, except we now give a good error message for invalid fields on `python_binary`, which we used to silently accept.

```
▶ ./v2 --no-print-exception-stacktrace run build-support/bin:check_banned_imports


ERROR: Invalid target build-support/bin:check_banned_imports: Unrecognized field `fake=1`. Valid fields for the target type `python_binary`: ['always_write_cache', 'compatibility', 'dependencies', 'emit_warnings', 'entry_point', 'ignore_errors', 'indices', 'inherit_path', 'platforms', 'provides', 'repositories', 'shebang', 'sources', 'tags', 'zip_safe'].
```

### Converting `HydratedStruct` -> `Target`

For now, we hydrate BUILD files into Targets by going from `eval() -> HydratedStruct -> Target`. `HydratedStruct` will do the bare minimum of hydration we need for a `Target`, e.g. resolving the `Address` and mapping the field `dependencies` to other `Address`es. (We might remove `HydratedStruct` in some future.)

We can't go from `TargetAdaptor -> Target` because `TargetAdaptor` will have already hydrated the `sources`.

This adds a pure function to convert `HydratedStruct -> Target`. A followup will convert this to a rule.

### New pattern (tentative design): rules expressing the minimum fields they need to operate

A key goal of the Target API is for rules to stop saying that they only work with certain target types, but to instead express which precise typed `Field`s they need to operate. For example, Black only needs `PythonSources` and doesn't care about any other fields.

To get this working with the engine, (for now), downstream rules should declare a new dataclass called `MyRuleFields`, e.g. `PythonBinaryFields`, which has an entry for each typed `Field`. This should expose the methods `.is_valid_target()` and `.create()`. 

The downstream rule will then request `PythonBinaryFields` as its input, and its upstream rule will filter out its collection of `Targets` (plural) via `PythonBinaryFields.is_valid_target()` to pass down instances of `PythonBinaryFields` where relevant. This is the same pattern we use for `lint.py` with `Linter.is_valid_target()`. As with `lint.py`, we can use unions to allow multiple downstream rules, e.g. `PythonBinaryFields` vs. `JavaBinaryFields`.

(The specific mechanism might change, e.g. using `SelectFields(EntryPoint, PythonBinarySources)` as the rule param instead of `PythonBinaryFields`. The important part is the need for a mechanism for rules to request the precise fields they need in their rule definition - less important is how we do that at the moment.)

### Also improves error messages

We use `TargetDefinitionError` to have more useful and structured error messages. In a followup, we'll want to make these more helpful. This is only a first pass.