Explicitly use backports.configparser (#6542)
### Problem

Currently `PYTHONCASEOK=1` would cause `import configparser` to load the system configparser instead of the backported one, causing

```
$ PYTHONCASEOK=1  ./pants -V
Exception caught: (<type 'exceptions.AttributeError'>)
  File "/Users/me/workspace/pants/src/python/pants/bin/pants_loader.py", line 75, in <module>
    main()
  File "/Users/me/workspace/pants/src/python/pants/bin/pants_loader.py", line 71, in main
    PantsLoader.run()
  File "/Users/me/workspace/pants/src/python/pants/bin/pants_loader.py", line 67, in run
    cls.load_and_execute(entrypoint)
  File "/Users/me/workspace/pants/src/python/pants/bin/pants_loader.py", line 60, in load_and_execute
    entrypoint_main()
  File "/Users/me/workspace/pants/src/python/pants/bin/pants_exe.py", line 38, in main
    PantsRunner(exiter, start_time=start_time).run()
  File "/Users/me/workspace/pants/src/python/pants/bin/pants_runner.py", line 35, in run
    bootstrap_options = options_bootstrapper.get_bootstrap_options()
  File "/Users/me/workspace/pants/src/python/pants/option/options_bootstrapper.py", line 171, in get_bootstrap_options
    self.construct_and_set_bootstrap_options()
  File "/Users/me/workspace/pants/src/python/pants/option/options_bootstrapper.py", line 162, in construct_and_set_bootstrap_options
    next_item = producer.send([filecontent_for(f) for f in files])
  File "/Users/me/workspace/pants/src/python/pants/option/options_bootstrapper.py", line 109, in produce_and_set_bootstrap_options
    pre_bootstrap_config = Config.load_file_contents(config_files_products)
  File "/Users/me/workspace/pants/src/python/pants/option/config.py", line 57, in load_file_contents
    return cls._meta_load(opener, file_contents, seed_values)
  File "/Users/me/workspace/pants/src/python/pants/option/config.py", line 89, in _meta_load
    parser.read_file(ini)

Exception message: ConfigParser instance has no attribute 'read_file'
```

### Solution

Use explicit `from backports import configparser`

### Result
```
$ PYTHONCASEOK=1  ./pants -V
1.10.0rc0
```