Improve error message for invalid input in `Get()`s (#11081)
Before:

> Exception: WithDeps(Inner(InnerEntry { params: {Specs, Console}, rule: Task(Task { product: List, can_modify_workunit: false, clause: [Addresses, ListSubsystem, Console], gets: [Get { output: UnexpandedTargets, input: Addresses }], func: pants.backend.project_info.list_targets:64:list_targets(), cacheable: false, display_info: DisplayInfo { name: "pants.backend.project_info.list_targets.list_targets", desc: Some("`list` goal"), level: Debug } }) })) did not declare a dependency on JustGet(Get { output: UnexpandedTargets, input: int })

After:

```
Engine traceback:
  in select
  in pants.backend.project_info.list_targets.list_targets
Traceback (most recent call last):
  File "/Users/eric/DocsLocal/code/projects/pants/src/python/pants/engine/internals/native.py", line 65, in generator_send
    res = func.send(arg)
  File "/Users/eric/DocsLocal/code/projects/pants/src/python/pants/backend/project_info/list_targets.py", line 79, in list_targets
    targets = await Get(UnexpandedTargets, Addresses, 123)
  File "/Users/eric/DocsLocal/code/projects/pants/src/python/pants/util/meta.py", line 182, in new_init
    prev_init(self, *args, **kwargs)
  File "/Users/eric/DocsLocal/code/projects/pants/src/python/pants/engine/internals/selectors.py", line 159, in __init__
    self.input = self._validate_input(input_arg1, shorthand_form=False)
  File "/Users/eric/DocsLocal/code/projects/pants/src/python/pants/engine/internals/selectors.py", line 201, in _validate_input
    f"Invalid Get. The third argument `{input_}` must have the exact same type as the "
TypeError: Invalid Get. The third argument `123` must have the exact same type as the second argument, pants.engine.addresses.Addresses, but had the type <class 'int'>.
```

Note that the stacktrace includes the offending `Get`, including the line and file where it's set. This is because we now eagerly validate in the Python constructor for `Get`.

We can only apply this new error message for non-union `Get` calls; the engine must handle type errors relating to `unions` because Python does not have knowledge of `UnionMembership` in the `Get` constructor.

Closes https://github.com/pantsbuild/pants/issues/8349.