Enable python-eval for pants source code.
This installs the PythonEval task in the compile phase for pants and
engages the python "compile" checks for pants source code in ci.  As a
result there are many missing BUILD dep fixes as well flagged by
python-eval in ci.

The python-eval checks add ~2 minutes to each ci shard, so ci is
restructured to be more fine grained in order to keep ci times ~6
minutes per shard.

Testing Done:
CI went green here:
  https://travis-ci.org/pantsbuild/pants/builds/50809395

Also ran the moved anonimizer tool:
```console
$ PANTS_DEV=1 ./pants= run src/python/pants/backend/jvm/tasks/jvm_compile:anonymize_zinc_analysis
...
22:33:14 00:01   [run]
22:33:14 00:01     [py]
22:33:14 00:01       [run]
Traceback (most recent call last):
  File "/tmp/tmptqC4pT/.bootstrap/_pex/pex.py", line 272, in execute
    self.execute_entry(entry_point, args)
  File "/tmp/tmptqC4pT/.bootstrap/_pex/pex.py", line 320, in execute_entry
    runner(entry_point)
  File "/tmp/tmptqC4pT/.bootstrap/_pex/pex.py", line 337, in execute_module
    runpy.run_module(module_name, run_name='__main__')
  File "/home/jsirois/.pyenv/versions/2.7.8/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/home/jsirois/.pyenv/versions/2.7.8/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jsirois/dev/3rdparty/jsirois-pants/src/python/pants/backend/jvm/tasks/jvm_compile/scala/bin/anonymize_analysis.py", line 45, in <module>
    main()
  File "/home/jsirois/dev/3rdparty/jsirois-pants/src/python/pants/backend/jvm/tasks/jvm_compile/scala/bin/anonymize_analysis.py", line 28, in main
    word_file = sys.argv[1]
IndexError: list index out of range

FAILURE: python {args} ... exited non-zero ({code})
```

Bugs closed: 1108

Reviewed at https://rbcommons.com/s/twitter/r/1773/