Error out on duplicate artifacts for jar publish.
This adds some extra validation to check_targets to ensure that we
don't have multiple libraries which provide the same artifact.

A nicely formatted error message is output in the event of a
conflict:

    DuplicateArtifactError: Multiple targets define the same artifacts!

      com.example-nail -> internal -> http://example.com
(/private/var/folders/wf/q7mqymv13kq1w7vkzq6y0fr4000258/T/tmpZRPxjZ_BUILD_ROOT/pushdb)
is defined by:
        a:a
        conflict:conflict

Testing Done:
Added a test to test_jar_publish.py.

CI went green here: https://travis-ci.org/gmalmquist/pants/builds/110481214

Bugs closed: 2941

Reviewed at https://rbcommons.com/s/twitter/r/3481/