Mypy cache no longer shared between resolves (#22112)
In my company's repository we have multiple resolves on the same python
version with different requirements. When running `pants check` on files
that are shared between the resolves sometimes (it is sporadic based on
cache state) we get errors on one of the resolves with missing libraries
that are not present in it, but are present in the other resolve (the
file itself doesn't use this package):
```
src/python/hs_build/version_upgrade/build_macos_x86_64_wheels.py:1: error: Cannot find implementation or library stub for module named "torch.nn.functional"  [import-not-found]
src/python/hs_build/version_upgrade/build_macos_x86_64_wheels.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

To avoid such cache inconsistencies I propose we scope the mypy cache by
resolve, so no such clashing can occur.