Add helpful error message to rule authors when merging non-digests (#8962)
### Problem
Several different times, rule authors have encountered issues where they try merging a non-digest with `DirectoriesToMerge`. This is especially common because we often try to merge digests coming from wrapper types like `InitInjectedDigest` and we forgot to unwrap the underlying digest. When this happens, the error message is particularly unhelpful:

```
Exception message: Internal logic error in scheduler: expected elements in `self._native._peek_cffi_extern_method_runtime_exceptions()`
```

While MyPy does catch most these issues now that our rule code is fully typed, there's sometimes a chicken-and-the-egg problem that the issue in the rule results in `./pants lint` not working to even be able to run MyPy. Also, most devs try running `./pants their-new-command` before running MyPy and this will help to eagerly catch the issue.

### Result
Now, we print an error message like this:

>             ValueError: Not all arguments are digests:
>
>            * ChrootedPythonSources(digest=Digest(fingerprint='7ec62cce797eaa13f80faef681089bda5dc6b0d9608c0a0ad974db97761b75f1', serialized_bytes_length=165))
>            * Pex(directory_digest=Digest(fingerprint='7d8f3a805c82c34b513c976beabaa2a50f10c47e15ed0885677e1fe05693ff28', serialized_bytes_length=107), output_filename='pytest-with-requirements.pex')

Closes https://github.com/pantsbuild/pants/issues/8907.