Update scalameta to support new given syntax (SIP-64) (#22921)
The new `given` syntax as described in [SIP-64][] has been released as
non-experimental in the Scala 3.6.x series. The default version of
scalameta used in pants doesn't support this syntax yet, so you'll get
compile errors during the dependency analysis stage (which is also very
confusing, since a user might assume it happened during the compilation
stage).

This PR updates `scalameta` to a more recent version which supports this
syntax.

Failing test case (without the scalameta update):

```
pants.engine.process.ProcessExecutionFailure: Process 'Scala source dependency analysis failed.' failed with exit code 899.
stdout:

stderr:
__source_to_analyze/Source.scala:8: error: ; expected but : found
    given intOrder: Ord[Int]:
                            ^
	at scala.meta.internal.parsers.Reporter.syntaxError(Reporter.scala:16)
```


[SIP-64]:
https://docs.scala-lang.org/sips/sips/typeclasses-syntax.html#7-cleanup-of-given-syntax