Suggest missing dependencies from target's transitive dependencies (#4171)
### Problem

Switching from `non-strict_deps` to `strict-deps` may result missing deps compile errors if deps used are from target's transitive deps but not declared as direct deps.

### Solution

This PR extracts the class names that are reported as `not found` from failure compile log and locate them in target's transitive classpath.

This approach is on a best-effort bsis:

* Compiler may not always report the not found class name, even though the error is due to missing deps. Work to improve scalac coverage is undergoing
* Newly introduced deps that are not in the transitive deps are not covered.

### Result
```
./pants compile testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist --compile-zinc-suggest-missing-deps
...
                       [info] Compiling 1 Java source to /Users/peiyu/github/pants/.pants.d/compile/zinc/66ac1c9326be/testprojects.src.java.org.pantsbuild.testproject.missingjardepswhitelist.missingjardepswhitelist/current/classes...
                       [error] /Users/peiyu/github/pants/testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist/MissingJarDepsWhitelist.java:4:1: package com.google.common.io does not exist
                       [error] import com.google.common.io.Closer;
                       [error] /Users/peiyu/github/pants/testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist/MissingJarDepsWhitelist.java:8:1: cannot find symbol
                       [error]   symbol:   class Closer
                       [error]   location: class org.pantsbuild.testproject.missingjardepswhitelist.MissingJarDepsWhitelist
                       [error]     Closer c = Closer.create();
                       [error] /Users/peiyu/github/pants/testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist/MissingJarDepsWhitelist.java:8:1: cannot find symbol
                       [error]   symbol:   variable Closer
                       [error]   location: class org.pantsbuild.testproject.missingjardepswhitelist.MissingJarDepsWhitelist
                       [error]     Closer c = Closer.create();
                       [error] Compile failed at Jan 10, 2017 11:23:09 AM [0.058s]
                       
11:23:09 00:03         [missing-deps-suggest]
                       
                       Found the following deps from target's transitive dependencies that provide the missing classes:
                         com.google.common.io.Closer: 3rdparty:guava
                       
                       If the above information is correct, please add the following to the dependencies of (testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist):
                         3rdparty:guava
                       
                   compile(testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist) failed: Zinc compile failed.
```