Fix: Example config for local filesystem caching (Cherry-pick of #20844) (#20849)
Using the original config snippet on a `pants` v.2.20 system results in:
> OptionsError: Value `file:///path/to/cache` from the
`[GLOBAL].remote_store_address` option is invalid: it doesn't have a
scheme that is supported by provider `reapi` from the
`[GLOBAL].remote_provider` option.
>
> Did you mean to use a provider that does support this scheme
(`experimental-file`) or to use a scheme that is supported by this
provider (`grpc://`, `grpcs://`)?

This is because the first key should be
[`remote_provider`](https://www.pantsbuild.org/2.20/reference/global-options#remote_provider)
instead

Co-authored-by: Dimitar Kovachev <lowvoltage@users.noreply.github.com>