Fix `fmt` with no specs (#16572)
Before: `TypeError: MultiGet() missing 1 required positional argument: '__arg0'`
After:  `<nothing>`

And with tests!

[ci skip-rust]
[ci skip-build-wheels]