always use an explicit ubuntu image
The release of `2.24.0rc2` failed:
https://github.com/pantsbuild/pants/actions/runs/12909883768/job/36005845441#step:3:19
```
  Version 3.7 was not found in the local cache
  Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

This is because the `publish` step was running on `ubuntu-latest`
which GitHub recently switched from Ubuntu 24
to 22. https://github.com/actions/runner-images/issues/10636 Which has
a different set of GitHub Python versions
<https://github.com/actions/python-versions> available.

Setting to an explicit image version lets us control the upgrade
cadence instead of rugs being pulled out from under.