allow `@rule`s to end in `yield Get(...)` (#8227)
### Problem

Previously, if a rule ended in `yield Get(A, B())`, the engine would raise an error like:
```
Exception: WithDeps(Inner(InnerEntry { params: {NoneType}, rule: Task(Task { product: A, clause: [Select { product: NoneType }], gets: [], func: final_yield(), cacheable: true }) })) did not declare a dependency on JustGet(Get { product: A, subject: B })
```

@gshuflin first discovered this issue.

### Solution

- Traverse the internal nodes of every single `yield` expression, not just assignments.
- Check for and raise an error message if a rule ends in a `yield Get()` expression.

### Result

Rules such as the following will now cause an error at `@rule` construction time:
```python
@rule(A, [C])
def f(c):
  yield Get(A, B(c))
# YieldVisitError: `yield Get(...)` in @rule is currently not allowed without an assignment.
```