Render only leaf rule graph errors, and improve error messages (#10311)
### Problem

As further described in #8808, `@rule` graph errors are currently effectively unusable for larger graphs because we render all failed entries rather than only the "root causes".

### Solution

Render the failed "leaves" of the graph, which are (most likely) to be the root causes of any failed nodes that depend on them.

Additionally, improve diagnostics by differentiating between:
1. Not having any installed rules that provide a type
    a. for a "Select", which could potentially be satisfied by installing a `RootRule`
    b. for a `Get`, which can only be satisfied by installing an additional rule
2. Having installed rules to provide a type, but none satisfiable.

### Result

Breaking an existing rule very deep in the graph (by attempting to `Get(DigestContents, PathGlobs)`, which we should fix, but I digress), goes from (note "snipped" lines):
#### Before:
```
Exception: Rules with errors: 82

<snip 266 lines>

  @rule(pants.engine.internals.build_files:61:parse_address_family(AddressMapper, BuildFilePreludeSymbols, Dir) -> AddressFamily, gets=[Get(Snapshot, PathGlobs), Get(DigestContents, Digest)]):
    No rule was available to compute BuildFilePreludeSymbols with parameter types (AddPrefix, Address, AddressSpecs, AddressWithOrigin, Addresses, AllSourceFilesRequest, ChangedRequest, Console, CreateDigest, DependenciesRequest, Digest, Dir, ExternalToolRequest, FieldSetsWithSourcesRequest, FilesystemSpecs, HydrateSourcesRequest, InferDependenciesRequest, InferPythonDependencies, InjectDependenciesRequest, InteractiveRunner, IsortRequest, MaybeExtractable, MergeDigests, MultiPlatformProcess, OptionsBootstrapper, OwnersRequest, PathGlobs, PexFromTargetsRequest, PexRequest, Process, PythonFmtTargets, RemovePrefix, Scope, SetupRequest, SnapshotSubset, SourceRootRequest, SpecifiedSourceFilesRequest, StripSnapshotRequest, StripSourcesFieldRequest, TargetsToValidFieldSetsRequest, TargetsWithSourcesRequest, TwoStepPexFromTargetsRequest, TwoStepPexRequest, UnstrippedPythonSourcesRequest, UrlToFetch, Workspace)

<snip 48 lines>
```
#### After:
```
Exception: Rules with errors: 8

<snip 20 lines>

  @rule(pants.engine.internals.build_files:61:parse_address_family(AddressMapper, BuildFilePreludeSymbols, Dir) -> AddressFamily, gets=[Get(Snapshot, PathGlobs), Get(DigestContents, Digest)]):
    No rule was able to compute BuildFilePreludeSymbols.:
      @rule(pants.engine.internals.build_files:35:evaluate_preludes(AddressMapper) -> BuildFilePreludeSymbols, gets=[Get(DigestContents, PathGlobs)]) for (AddPrefix, Address, AddressSpecs, Addresses, AllSourceFilesRequest, ChangedRequest, Console, CreateDigest, DependenciesRequest, Digest, Dir, ExternalToolRequest, FieldSetsWithSourcesRequest, HydrateSourcesRequest, InferDependenciesRequest, InferPythonDependencies, InjectDependenciesRequest, InteractiveRunner, MaybeExtractable, MergeDigests, MultiPlatformProcess, OptionsBootstrapper, OwnersRequest, PathGlobs, PexFromTargetsRequest, PexRequest, Process, PythonModule, PythonTestFieldSet, RemovePrefix, Scope, SnapshotSubset, SourceRootRequest, SpecifiedSourceFilesRequest, Specs, StripSnapshotRequest, StripSourcesFieldRequest, TargetsToValidFieldSetsRequest, TargetsWithSourcesRequest, TwoStepPexFromTargetsRequest, TwoStepPexRequest, UnstrippedPythonSourcesRequest, UrlToFetch, Workspace, WrappedTestFieldSet): Was unfulfillable.
```

Fixes #8808.