add missing `flush`/`close` methods to `PyStdioRead` / `PyStdioWrite` (#23122)
Add missing `close` and `flush` methods to `PyStdioRead` /
`PyStdioWrite` to avoid this warning:

```
Exception ignored while finalizing file <_io.TextIOWrapper encoding='UTF-8'>:
Traceback (most recent call last):
  File "REDACTED/pants/src/python/pants/init/logging.py", line 227, in initialize_stdio_raw
    sys.__stdin__, sys.__stdout__, sys.__stderr__ = sys.stdin, sys.stdout, sys.stderr  # type: ignore[misc,assignment]
AttributeError: 'builtins.PyStdioRead' object has no attribute 'close'
Exception ignored while finalizing file <_io.BufferedReader>:
Traceback (most recent call last):
  File "REDACTEDpants/src/python/pants/init/logging.py", line 227, in initialize_stdio_raw
    sys.__stdin__, sys.__stdout__, sys.__stderr__ = sys.stdin, sys.stdout, sys.stderr  # type: ignore[misc,assignment]
AttributeError: 'builtins.PyStdioRead' object has no attribute 'close'
```