Use a released version of cargo-audit.
The latest release includes the `--ignore` feature we use, so upgrade to
`0.7.0`.

Testing this locally revealed a new vulnerability:
```
$ ./build-support/bin/ci.py --cargo-audit
...
    Finished release [optimized] target(s) in 6m 11s
   Replacing /home/jsirois/.cache/pants/rust/cargo/bin/cargo-audit
    Replaced package `cargo-audit v0.7.0` with `cargo-audit v0.6.1 (https://github.com/RustSec/cargo-audit?rev=1c298bcda2c74f4a1bd8f0d8482b3577ee94fbb3#1c298bcd)` (executable `cargo-audit`)
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 33 security advisories (from /home/jsirois/.cache/pants/rust/cargo/advisory-db)
    Scanning src/rust/engine/Cargo.lock for vulnerabilities (334 crate dependencies)
error: Vulnerable crates found!

ID:	 RUSTSEC-2019-0011
Crate:	 memoffset
Version: 0.2.1
Date:	 2019-07-16
URL:	 https://github.com/Gilnaa/memoffset/issues/9#issuecomment-505461490
Title:	 Flaw in offset_of and span_of causes SIGILL, drops uninitialized memory of arbitrary type on panic in client code
Solution: upgrade to: >= 0.5.0

error: 1 vulnerability found!
Cargo audit failure
```

We don't directly depend on `memoffset`, our root direct dep here is
`tokio-threadpool`:
```
$ .cd src/rust/engine && ./../../build-support/bin/native/cargo tree -p memoffset -i
memoffset v0.2.1
└── crossbeam-epoch v0.7.1
    └── crossbeam-deque v0.7.1
        └── tokio-threadpool v0.1.15
            ...
            ├── store v0.1.0 (/home/jsirois/dev/pantsbuild/pants/src/rust/engine/fs/store)
            ...
```

There is no newer version of `tokio-threadpool`, but a target update
solves the issue and gets us to `memoffest` `0.5.11`:
```
$ ./build-support/bin/native/cargo update --manifest-path src/rust/engine/Cargo.toml -p tokio-threadpool --aggressive
    Updating crates.io index
    Updating arrayvec v0.4.10 -> v0.4.11
    Updating autocfg v0.1.4 -> v0.1.5
    Updating crossbeam-epoch v0.7.1 -> v0.7.2
    Updating crossbeam-utils v0.6.5 -> v0.6.6
    Updating libc v0.2.59 -> v0.2.60
    Updating log v0.4.6 -> v0.4.8
    Updating memoffset v0.2.1 -> v0.5.1
    Updating rand_core v0.4.0 -> v0.4.2
      Adding scopeguard v1.0.0
    Updating spin v0.5.0 -> v0.5.1
```