Pin a conan dep that was floating to a version that was not compatible with python 2. (#6825)
### Problem

Master is currently failing to translate `typed_ast` on python 2, with:
```
**** Failed to install typed-ast-1.1.0 (caused by: NonZeroExit("received exit code 1 during execution of `['/home/travis/build/pantsbuild/pants/build-support/pants_dev_deps.venv/bin/python2.7', '-', 'bdist_wheel', '--dist-dir=/tmp/tmpJy273C']` while trying to execute `['/home/travis/build/pantsbuild/pants/build-support/pants_dev_deps.venv/bin/python2.7', '-', 'bdist_wheel', '--dist-dir=/tmp/tmpJy273C']`",)
 ):
 stdout:
 
 stderr:
 Error: typed_ast only runs on Python 3.3 and above.
```

### Solution

Pin a conan dep that was floating to a version that was not compatible with py2.

### Result

Broken tests are fixed.