fix link format in aarch64 runner instructions (#21881)
This fixes the docs workflow:
https://github.com/pantsbuild/pantsbuild.org/actions/runs/13019671126/job/36317230829?pr=312
```
Error:  Client bundle compiled with errors therefore further build is impossible.
Error: MDX compilation failed for file "/home/runner/work/pantsbuild.org/pantsbuild.org/docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx"
Cause: Markdown link URL is mandatory in "docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx" file (title: build-support/packer/runson/runson.pkr.hcl, line: 26).
Details:
Error: Markdown link URL is mandatory in "docs/docs/contributions/releases/github-actions-linux-aarch64-runners.mdx" file (title: build-support/packer/runson/runson.pkr.hcl, line: 26).
Error: Process completed with exit code 1.
```