docs: Remove targets of the form dir/BUILD:target which cause errors
ValueError: Spec tests/java/com/pants/examples/hello/greet/BUILD:greet
has BUILD as the last path part and BUILD is reserved files

Reviewed at https://rbcommons.com/s/twitter/r/853/