Update help message for ./pants goal goals  (was ./pants goals)
./pants goals fails with a message:

BadSpecError: BUILD file does not exist at: /Users/zundel/Src/pants/goals/BUILD

Testing Done:
manual inspection of the help output.

Bugs closed: 644

Reviewed at https://rbcommons.com/s/twitter/r/1128/