Update hdrhistogram to version 0.10.7 (#23435)
## Problem

Pants 2.32.0+ upgraded to python 3.14 and the hdrhistogram dependency
(for stats.log=true) doesn't include binary wheels for python 3.14 until
version 0.10.7. If the host running pants doesn't have `clang` enabled,
then the build can fail.

e.g.

```
error: command 'clang' failed: No such file or directory
```

## Solution

Version 0.10.7 of hdrhistogram includes binaries for python 3.14, ref:
https://github.com/HdrHistogram/HdrHistogram_py/issues/61