Move excludes logic into cmd_line_spec_parser so it can filter out broken build targets.
This is a revamp of https://rbcommons.com/s/twitter/r/930/.  The difference is that
this is now much easier after the options refactoring.

Testing Done:
Added unit test.

Created a bogus BUILD file on the path:

```
mkdir -p some/dir
echo "BOGUS" >>some/dir/BUILD
```

and tried:

PANTS_DEV=1 ./pants goal compile :: --exclude-target-regexp='.*some/dir.*' --exclude-target-regexp='.*android.*'

Before this change, it fails:

```
AddressLookupError: name 'BOGUS' is not defined
 while executing BUILD file /Users/zundel/Src/pants/some/dir/BUILD
 Loading addresses from 'some/dir' failed.
```

Now, if you exclude the bad build file path, you can get past it.

Bugs closed: 903

Reviewed at https://rbcommons.com/s/twitter/r/1566/