Fix pants test libraries missing dependencies
Currently on master if you don't have PANTS_DEV=1, pants_test:all target fails.

Fixed following python test targets:
1. tests/python/pants_test/test_utf8_header.py F due to
BackendConfigurationError: Failed to load the pants.backend.core.register backend: No module named goal

2.tests/python/pants_test/base/test_build_configuration.py:16: in <module>
    from pants.base.build_configuration import BuildConfiguration
/var/folders/t_/ck6c3zvj2z5cg77dqx2kh8tr0000gp/T/tmpy8_YJ_/pants/base/build_configuration.py:12: in <module>
    from pants.base.build_file_aliases import BuildFileAliases
E   ImportError: No module named build_file_aliases

3. tests/python/pants_test/java/test_executor.py:18: in <module>
    from pants.java.executor import SubprocessExecutor
/var/folders/t_/ck6c3zvj2z5cg77dqx2kh8tr0000gp/T/tmp3lxmyq/pants/java/executor.py:18: in <module>
    from pants.base.build_environment import get_buildroot
E   ImportError: No module named build_environment

4. >   ???
E   ImportError: No module named authentication.netrc_util

Testing Done:
CI passes as usual.
https://travis-ci.org/pantsbuild/pants/builds/30308887

On my branch:- Following command succeeds.
 rm pants.pex && ./pants tests/python/pants_test:all

Bugs closed: 355

Reviewed at https://rbcommons.com/s/twitter/r/685/