[internal] Use system-installed Go rather than installing via Pants (#13007)
Closes https://github.com/pantsbuild/pants/issues/12772. We do this for performance to avoid copying the Go SDK into the chroot every time. This should be replaced once we can support immutable caches.

Users now set a single expected Go version for the whole project, which is similar to how we originally required a single Go version to download. If we detect Go with an invalid version, we'll print a nice error message:

```
pants.engine.process.BinaryNotFoundError: Cannot find a `go` binary with the expected version of 1.15 (set by `[golang].expected_version`).

Found these `go` binaries, but they had different versions:

* /opt/homebrew/bin/go, 1.17

To fix, please install the expected version (https://golang.org/doc/install) and ensure that it is discoverable via the option `[golang].go_search_paths`, or change `[golang].expected_version`.
```

https://github.com/pantsbuild/pants/issues/13005 tracks adding more flexibility.

[ci skip-rust]
[ci skip-build-wheels]