Fix publishing and also add integration tests
Fix publishing errors
1. Fix no config javadoc found for targets with no depdencies.
==== stderr ====
                     Exception in thread "main" java.text.ParseException: Problem occurred while parsing ivy file: Cannot add artifact 'example.jar(javadoc)' to configuration 'javadoc' of module com.twitter#example;0.0.1-SNAPSHOT because this configuration doesn't exist! in file:/Users/tdesai/projects/pants/.pants.d/publish/publish/com.twitter/example/ivy-0.0.1-SNAPSHOT.xml

2. Add Integration tests

Testing Done:
locally:
 ./pants tests/python/pants_test/tasks:jar_publish_integratio
tests/python/pants_test/tasks/test_jar_publish_integration.py ..

============================================================================= 2 passed in 23.32 seconds =============================================================================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/private/var/folders/t_/ck6c3zvj2z5cg77dqx2kh8tr0000gp/T/tmpKYikI8/.deps/twitter.common.dirutil-0.3.0-py26-none-any.whl/twitter/common/dirutil/__init__.py", line 61, in _mkdtemp_atexit_cleaner
    for td in _MKDTEMP_DIRS.pop(os.getpid(), []):
AttributeError: 'NoneType' object has no attribute 'pop'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/private/var/folders/t_/ck6c3zvj2z5cg77dqx2kh8tr0000gp/T/tmpKYikI8/.deps/twitter.common.dirutil-0.3.0-py26-none-any.whl/twitter/common/dirutil/__init__.py", line 61, in _mkdtemp_atexit_cleaner
    for td in _MKDTEMP_DIRS.pop(os.getpid(), []):
AttributeError: 'NoneType' object has no attribute 'pop'
tests.python.pants_test.tasks.jar_publish_integration                           .....   SUCCESS
[tw-172-25-20-142 pants]$ ./pants tests/python/pants_test/tasks:jar_publish_integration
Build operating on targets: OrderedSet([PythonTests(tests/python/pants_test/tasks/BUILD:jar_publish_integration)])

Bugs closed: 120

Reviewed at https://rbcommons.com/s/twitter/r/356/