Kill leftover imports handling from early efforts.
PythonLibrary targets have never had jar_dependencies so
this was likely a broken code-path since inception in
https://rbcommons.com/s/twitter/r/592/

Testing Done:
Hit this code-path in another branch:
```console
...
10:24:47 00:03     [protoc]
                   Left with unexpected unconsumed gen targets:
                   	JvmBinary(BuildFileAddress(/home/jsirois/dev/3rdparty/jsirois-pants2/testprojects/src/java/com/pants/testproject/utf8proto/BUILD, utf8proto)) -> set([JavaProtobufLibrary(BuildFileAddress(/home/jsirois/dev/3rdparty/jsirois-pants2/testprojects/src/protobuf/com/pants/testproject/utf8proto/BUILD, utf8proto))])
                   	Dependencies(BuildFileAddress(/home/jsirois/dev/3rdparty/jsirois-pants2/testprojects/src/java/com/pants/testproject/proto-ordering/BUILD, proto-ordering)) -> set([JavaProtobufLibrary(BuildFileAddress(/home/jsirois/dev/3rdparty/jsirois-pants2/testprojects/src/protobuf/com/pants/testproject/proto-ordering/BUILD, protos))])
                   Invalidated 4 targets containing 4 payload files.
               FAILURE
Traceback (most recent call last):
  File "/home/jsirois/dev/3rdparty/jsirois-pants2/pants.pex/.bootstrap/_pex/pex.py", line 272, in execute
    self.execute_entry(entry_point, args)
  File "/home/jsirois/dev/3rdparty/jsirois-pants2/pants.pex/.bootstrap/_pex/pex.py", line 320, in execute_entry
    runner(entry_point)
  File "/home/jsirois/dev/3rdparty/jsirois-pants2/pants.pex/.bootstrap/_pex/pex.py", line 343, in execute_pkg_resources
    runner()
  File "pants/bin/pants_exe.py", line 66, in main
  File "pants/bin/pants_exe.py", line 61, in _run
  File "pants/bin/goal_runner.py", line 163, in run
  File "pants/bin/goal_runner.py", line 246, in _do_run
  File "pants/engine/engine.py", line 27, in execute
  File "pants/engine/round_engine.py", line 210, in attempt
  File "pants/engine/round_engine.py", line 46, in attempt
  File "pants/backend/codegen/tasks/code_gen.py", line 131, in execute
  File "pants/backend/codegen/tasks/protobuf_gen.py", line 219, in createtarget
  File "pants/backend/codegen/tasks/protobuf_gen.py", line 263, in _create_python_target
AttributeError: 'PythonLibrary' object has no attribute 'jar_dependencies'

test failure in testprojects/
```

CI went green here: https://travis-ci.org/pantsbuild/pants/builds/47267371

Bugs closed: 944

Reviewed at https://rbcommons.com/s/twitter/r/1614/