Add "did you mean" functionality to runtime Param mismatches. (#8315)
### Problem

When a `@rule` graph has been correctly constructed, but has different requirements than you expected, it can be challenging to figure out which `Params` are necessary to make a `product_request`.

Moreover, it's not obvious that all incoming `Param` types for `product_request` must be registered via `RootRule`.

### Solution

Add "did you mean" type functionality that renders the `Params` for other `@rule` graph roots that are able to produce the type you wanted. Example:
```
Exception: No installed @rules can compute SourceRootStrippedSources for input Params((HydratedTarget+SourceRootConfig)), but there were rules that could compute it using:
  Params((Address+OptionsBootstrapper))
  Params((Address+SourceRootConfig))
```

And when an unregistered Param type is used in a `product_request`:
```
Exception: Types that will be passed as Params at the root of a graph need to be registered via RootRule:
  Any
```