Fixup pants.jvm package.
The package was missing an __init__.py.
Additionally pants.jvm.jvm_tool_task_mixin had under-reported deps.

Testing Done:
Was:
$ PANTS_DEV=1 ./pants
*** Running pants in dev mode from /home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/bin/pants_exe.py ***
Traceback (most recent call last):
  File "/home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/bin/pants_exe.py", line 21, in <module>
    from pants.commands.register import register_commands
  File "/home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/commands/register.py", line 8, in <module>
    from pants.commands.goal import Goal
  File "/home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/commands/goal.py", line 31, in <module>
    from pants.goal import Context, GoalError, Phase, register
  File "/home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/goal/register.py", line 11, in <module>
    from pants.tasks.antlr_gen import AntlrGen
  File "/home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/tasks/antlr_gen.py", line 12, in <module>
    from pants.jvm.jvm_tool_task_mixin import JvmToolTaskMixin
ImportError: No module named jvm.jvm_tool_task_mixin

No longer fails fast:
$ PANTS_DEV=1 ./pants
*** Running pants in dev mode from /home/jsirois/dev/3rdparty/pantsbuild-pants/src/python/pants/bin/pants_exe.py ***
Pants 0.1.0

Usage:
  ./pants goal [option ...] [goal ...] [target...]  Attempt the specified goals.
  ./pants goal help                                 Get help.
  ./pants goal help [goal]                          Get help for the specified goal.
  ./pants goal goals                                List all installed goals.

  [target] accepts two special forms:
    dir:  to include all targets in the specified directory.
    dir:: to include all targets found recursively under the directory.

Friendly docs:
  http://pantsbuild.github.io/

Global options:
  -h, --help              Show this help message.
  -t CONN_TIMEOUT, --timeout=CONN_TIMEOUT
                          Number of seconds to wait for http connections.
  -x, --time              Times goal phases and outputs a report.
  -e, --explain           Explain the execution of goals.
  -k, --kill-nailguns     Kill nailguns before exiting
  -d LOGDIR, --logdir=LOGDIR
                          [none] Write logs to files under this directory.
  -l LOG_LEVEL, --level=LOG_LEVEL
                          [info] Set the logging level [debug, info, warn].
  -q, --quiet             Squelches all console output apart from errors.
  --no-colors             Do not colorize log messages.
  --read-from-artifact-cache, --no-read-from-artifact-cache
                          Read build artifacts from cache, if available.
  --write-to-artifact-cache, --no-write-to-artifact-cache

Bugs closed: 135

Reviewed at https://rbcommons.com/s/twitter/r/378/