Kill unused coverage dep - this is an indirect dep we need not specify.
Also fixup coverage handling in the pytest goal:
+ Fixup cov_setup's use of itertools.chain.
+ Fix config template encoding, coverage was failing under ci with:
$ PANTS_PY_COVERAGE=1 ./build-support/bin/ci.sh
...
Traceback (most recent call last):
  File "/home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/pants.pex/pants/backend/python/test_builder.py", line 186, in _run_python_tests
    coverage_rc, args = self.cov_setup(targets)
  File "/home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/pants.pex/pants/backend/python/test_builder.py", line 140, in cov_setup
    cp = generate_coverage_config(targets)
  File "/home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/pants.pex/pants/backend/python/test_builder.py", line 66, in generate_coverage_config
    cp.readfp(Compatibility.StringIO(DEFAULT_COVERAGE_CONFIG))
  File "/home/jsirois/.pyenv/versions/2.6.8/lib/python2.6/ConfigParser.py", line 305, in readfp
    self._read(fp, filename)
  File "/home/jsirois/.pyenv/versions/2.6.8/lib/python2.6/ConfigParser.py", line 482, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: <???>, line: 2
'\x00[\x00r\x00u\x00n\x00]\x00\n'
Failed to run test!

FAILURE