Improve Docker undefined build arg behavior (#13723)
* Improve error message on missing env var.

Example output:

    $ ./pants --no-print-stacktrace package testprojects/src/python/docker:test-example
    16:09:01.46 [INFO] Initializing scheduler...
    16:09:01.80 [INFO] Scheduler initialized.
    16:09:07.33 [ERROR] 1 Exception encountered:

      DockerBuildEnvironmentError: The docker environment variable 'TEST_VERSION' is undefined. Either add a value for this variable to `[docker].env_vars`, or set a value in Pants's own environment.

[ci skip-rust]

[ci skip-build-wheels]