Fix errors and warnings in `./cargo doc`, and run in CI (#17908)
This fixes `./cargo doc`: before this PR, it would fail with several errors (and some warnings):

- Standardise on a single version of `bollard-stubs`. Having two resulted in the warning below. (Having one version also seems like it likely cuts total build time down a little bit since `bollard-stubs` takes a fair time (10s) to compile on my M1 Mac.)
  ```
  warning: output filename collision.
  The lib target `bollard-stubs` in package `bollard-stubs v1.42.0-rc.4 (https://github.com/fussybeaver/bollard.git?rev=2d66d11b44aeff0373ece3d64a44b243e5152973#2d66d11b)` has the same output filename as the lib target `bollard-stubs` in package `bollard-stubs v1.42.0-rc.3`.
  Colliding filename is: /Users/huon/projects/pantsbuild/pants/src/rust/engine/target/doc/bollard_stubs/index.html
  The targets should have unique names.
  This is a known bug where multiple crates with the same name use
  the same path; see <https://github.com/rust-lang/cargo/issues/6313>.
  ```
- Use `<https://...>` for links, instead of just plain `https://...` because rustdoc complains, e.g.:
  ```
  error: this URL is not a hyperlink
     --> task_executor/src/lib.rs:149:7
      |
  149 |   /// https://docs.rs/tokio/0.2.20/tokio/task/struct.JoinHandle.html
      |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://docs.rs/tokio/0.2.20/tokio/task/struct.JoinHandle.html>`
      |
      = note: bare URLs are not automatically turned into clickable links
  ```
- Add backticks around some text that's mean to be literal code, but is almost HTML (`Option<DirectoryDigest>`).
- Disable the automatic generation of doc comments for some specific protobuf fields, because they contain invalid HTML:
  ```
  warning: unclosed HTML tag `ip`
     --> /Users/huon/projects/pantsbuild/pants/src/rust/engine/target/debug/build/protos-eab05d27eca6b7b0/out/google.rpc.rs:268:32
      |
  268 |     /// For example, "clientip:<ip address of client>" or "project:<Google
      |                                ^^^
      |
      = note: `#[warn(rustdoc::invalid_html_tags)]` on by default
  
  ...
  warning: unclosed HTML tag `owner`
     --> /Users/huon/projects/pantsbuild/pants/src/rust/engine/target/debug/build/protos-eab05d27eca6b7b0/out/google.rpc.rs:367:26
      |
  367 |   /// For example, "user:<owner email>" or "project:<Google developer project
      |                          ^^^^^^
  ```

This PR also adds a `./cargo doc` invocation to CI, to stop this regressing in future. This seems to take ~1.5 minutes. I don't know if it is worth the time: it may just be better to fix this on demand, if/when it breaks. Another option would be to turn off `deny(warnings)` when running with rustdoc (`#[deny(warnings)]` -> `#![cfg_attr(not(doc), deny(warnings))]`), so that any regressions in future at least do not block `./cargo doc`.

Background: I've been poking at the Rust core little bit, and have found it a bit hard to understand what's going on with certain parts (e.g. the generated protobuf wrappers). Having access to this documentation locally (`./cargo doc --open`) was helpful.