Fix harmless error rendered when stdin is closed under pantsd (#9828)
### Problem

Closing `stdin` with the existing python client (such as occurs in script environments with explicitly empty stdin) currently triggers a harmless warning in the thread that manages stdin:
```
Exception in thread NailgunStreamWriter:
Traceback (most recent call last):
  File "/Users/stuhood/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/stuhood/src/pants/src/python/pants/java/nailgun_io.py", line 109, in run
    self.do_run(readable_fds, errored_fds)
  File "/Users/stuhood/src/pants/src/python/pants/java/nailgun_io.py", line 128, in do_run
    self.stop_reading_from_fd(fileno)
  File "/Users/stuhood/src/pants/src/python/pants/java/nailgun_io.py", line 97, in stop_reading_from_fd
    self._in_fds.remove(fileno)
ValueError: list.remove(x): x not in list
```
This occurs because `select` can return the fd as both readable-but-empty and error'ed when it is closed, which caused two attempts to `stop_reading_from_fd`.

### Solution

Allow for multiple calls to `_stop_reading_from_fd`.

[ci skip-rust-tests]
[ci skip-jvm-tests]