Patch up migrate_config
- Patch up migrate_config with missing dependency.
- Move partition_size_hint into the correct section in pants.ini as pointed out by migrate_config
- Fix the 'target' and 'source' config options for [compile.java] (remove quotes)

Testing Done:
Before adding this dep, got:

  File "/Users/zundel/Src/pants/dist/migrate_config.pex/pants/option/migrate_config.py", line 13, in <module>
ImportError: cannot import name custom_types

when trying to execute migrate_config.

Bugs closed: 832

Reviewed at https://rbcommons.com/s/twitter/r/1409/