Add runtime type checking to Fields (#9353)
## Problem

Even when we put type hints on `Field`s for what we expect their `raw_value` to be, we have no way of actually enforcing this beyond runtime type checks. For example, we expect the value for `ZipSafe` to be `Optional[bool]`, but there is nothing stopping users from doing this:

```python
python_binary(
  zip_safe=123,
)
```

Without runtime type checks, this means that our type hints would now be lies and we risk getting weird `TypeError`s that are hard to debug when the value is different than what we expected.

## Solution

Add runtime type checking to each of the `PrimitiveField` helpers, e.g. `BoolField` and `StringField`. This means that almost none of the actual concrete target types had to change - they get the validation automatically thanks to inheritance.

### Stop using `ClassVar` when unnecessary

This also stops annotating all `Field` and `Target` subclasses with `ClassVar`, which John pointed out is redundant. Turns out, it indeed is redundant. See https://docs.python.org/3/library/dataclasses.html#class-variables for how class properties work with dataclasses. This greatly reduces boilerplate.

### Mark `PrimitiveField` subclasses with `ABCMeta`

This ensures that no one ever tries to instantiate `StringField`, `BoolField`, etc. These are only superclasses for boilerplate reduction.

### Fix `Files` target registration

It was missing an `alias` and its `register.py` still used `targets()`, rather than `targets2()` (see https://github.com/pantsbuild/pants/pull/9334).

## Result

Invalid boolean field:

> ERROR: The 'zip_safe' field in target build-support/bin:check_banned_imports must be a boolean, but was `123` with type `int`.

Invalid string sequence field:

> ERROR: The 'tags' field in target build-support/bin:check_banned_imports must be an iterable of strings (e.g. a list of strings), but was `{1, 2}` with type `set`.

Non-python `sources`:

> ERROR: The 'sources' field in target build-support/bin:check_banned_imports must only contain Python files that end in `.py`, but it had these non-Python files: ['build-support/bin/check_clippy.sh'].

Binary target with > 1 source file:

> ERROR: The 'sources' field in target build-support/bin:check_banned_imports must only have 0 or 1 files because it is a binary target, but it has 2 sources: ['build-support/bin/check_banned_imports.py', 'build-support/bin/check_header.py'].
>
> To use any additional files, put them in a `python_library` and then add that `python_library` as a `dependency`.