Update console and indicatif deps (Cherry-pick of #20998) (#21002)
These dependencies were using a git dependency due to unmerged
bug-fixes. These fixes have now been merged and are available in the
latest releases:

- https://github.com/console-rs/console/pull/186
- https://github.com/console-rs/indicatif/pull/608

In addition, I think the commits in question may've disappeared? E.g.
the fresh build on the new CI platform in had this error:
https://github.com/pantsbuild/pants/pull/20997

```
    Updating git repository `https://github.com/tgolsson/console.git`
error: failed to load source for dependency `console`

Caused by:
  Unable to update https://github.com/tgolsson/console.git?rev=5483880905f384679d322e83c37180f122951995#54838809

Caused by:
  revspec '5483880905f384679d322e83c37180f122951995' not found; class=Reference (4); code=NotFound (-3)
```

Thus, this is marked for cherry-picking back to our active branches.

Co-authored-by: Huon Wilson <huon@exoflare.io>