Revert "Load the bootstrapped zinc compiler from the zinc server's classpath. (#8753)" (#9226)
This reverts commit 9c72c1367db31ed37353e5d700d453de3d519441.

### Problem
The code in our zinc wrapper is in an inconsistent state with the latest published version (`0.0.17`).

This means that **one does not simply** publish a local jar for zinc with the following steps:
* Publish the jar to one's local m2 repository
```
./pants publish.jar --named-snapshot=master  --local-snapshot --publish-jar-local=~/.m2/repository --no-dryrun --no-prompt src/scala/org/pantsbuild/zinc/compiler
```
* Update the `_ZINC_COMPILER_VERSION` in `src/python/pants/backend/jvm/subsystems/zinc.py` to "master"
* Compile some jvm code

without incurring ~the wrath of Sauron~ this zinc error:
```
See zinc-compiler --help for information about options
Error: Unknown option -compiled-bridge-jar
Error: Unknown option -scala-path
Try --help for more information.
```

### Solution

Revert the change to zinc that added these two options but wasn't fully followed through until it is time to follow through.

### Result

I am able to iterate on the zinc code and test my changes.