Fix Pytest XML reports and Coverage breaking with remote execution (cherrypick of #10136) (#10324)
When running pytest with JUnit XML generation enabled, the Pants pytest_runner [uses `output_directories` instead of `output_files` to make the output file known to the process executor](https://github.com/pantsbuild/pants/blob/master/src/python/pants/backend/python/rules/pytest_runner.py#L237-L245). This works fine with local execution but breaks with remote execution because RE servers can skip `output_directories` that are not in fact directories.

This issue manifests as errors like this:

```
$ ./pants --pytest-junit-xml-dir=dist/test-results [remote-config options] test XXX
05:07:26.01 [INFO] Completed: Run Pytest for XXX
05:07:26.02 [WARN] Failed to generate JUnit XML data for XXX.
05:07:26.02 [INFO] Tests failed: XXX
𐄂 XXX
ERROR: --junitxml must be a filename, given: XXX.xml
```

Use `output_files` instead for the JUnit XML generation file.

The test runs and JUnit XML is properly generated and written to the local filesystem.

Co-authored-by: Tom Dyas <tdyas@toolchain.com>