Format suggested deps for easy cut & paste into BUILD file (#4711)
### Problem

The suggested deps are great, but when I get them I have to manually reformat them
for use in the dependencies array of my BUILD file.

### Solution

Format the suggested dependencies in a way that can be easily cut & pasted into a BUILD file. Also added a reminder to keep the dependencies in the BUILD file sorted, because if someone is doing a cut & paste of these additional dependencies they might forget to resort their dependencies.

### Result

```
./pants compile testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist --compile-zinc-suggest-missing-deps
...
13:55:30 00:05         [zinc]
                       [info] Compiling 1 Java source to /Users/sbrenn/workspace/pants/.pants.d/compile/zinc/c95338cea9cc/testprojects.src.java.org.pantsbuild.testproject.missingjardepswhitelist.missingjardepswhitelist/current/classes...
                       [error] /Users/sbrenn/workspace/pants/testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist/MissingJarDepsWhitelist.java:4:1: package com.google.common.io does not exist
                       [error] import com.google.common.io.Closer;
                       [error] /Users/sbrenn/workspace/pants/testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist/MissingJarDepsWhitelist.java:8:1: cannot find symbol
                       [error]   symbol:   class Closer
                       [error]   location: class org.pantsbuild.testproject.missingjardepswhitelist.MissingJarDepsWhitelist
                       [error]     Closer c = Closer.create();
                       [error] /Users/sbrenn/workspace/pants/testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist/MissingJarDepsWhitelist.java:8:1: cannot find symbol
                       [error]   symbol:   variable Closer
                       [error]   location: class org.pantsbuild.testproject.missingjardepswhitelist.MissingJarDepsWhitelist
                       [error]     Closer c = Closer.create();
                       [error] Compile failed at Jun 28, 2017 1:55:30 PM [0.079s]

13:55:30 00:05         [missing-deps-suggest]

                       Found the following deps from target's transitive dependencies that provide the missing classes:
                         com.google.common.io.Closer: 3rdparty:guava

                       If the above information is correct, please add the following to the dependencies of (testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist):
                         '3rdparty:guava',

                   compile(testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist) failed: Zinc compile failed.
FAILURE: Compilation failure: Failed jobs: compile(testprojects/src/java/org/pantsbuild/testproject/missingjardepswhitelist:missingjardepswhitelist)
```