Kill unused coverage dep - this is an indirect dep we need not specify.
Also fixup coverage handling in the pytest goal:
+ Fixup cov_setup's use of itertools.chain.
+ Fix config template encoding, coverage was failing under ci with:
$ PANTS_PY_COVERAGE=1 ./build-support/bin/ci.sh
...
Traceback (most recent call last):
  File "/home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/pants.pex/pants/backend/python/test_builder.py", line 186, in _run_python_tests
    coverage_rc, args = self.cov_setup(targets)
  File "/home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/pants.pex/pants/backend/python/test_builder.py", line 140, in cov_setup
    cp = generate_coverage_config(targets)
  File "/home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/pants.pex/pants/backend/python/test_builder.py", line 66, in generate_coverage_config
    cp.readfp(Compatibility.StringIO(DEFAULT_COVERAGE_CONFIG))
  File "/home/jsirois/.pyenv/versions/2.6.8/lib/python2.6/ConfigParser.py", line 305, in readfp
    self._read(fp, filename)
  File "/home/jsirois/.pyenv/versions/2.6.8/lib/python2.6/ConfigParser.py", line 482, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
  MissingSectionHeaderError: File contains no section headers.
  file: <???>, line: 2
  '\x00[\x00r\x00u\x00n\x00]\x00\n'
  Failed to run test!

  FAILURE

Testing Done:
There are still issues here on the actual coverage - notice its not finding the src/python and thats because we now defeat the parallel src/tests assumptions of test_builder.py and we do not manually override this with coverage kwargs in out PythonTests targets.  I've filed this issue to track fixing that: https://github.com/pantsbuild/pants/issues/231

Also, the integration tests fail with coverage enabled - I've filed this issue to track that: https://github.com/pantsbuild/pants/issues/232

That said - this is forward progress, we have minimal deps and coverage doesn't blow up on unicode/code errors any longer:
$ PANTS_PY_COVERAGE=1 ./build-support/bin/ci.sh
...
23:40:49 00:01   [test]
23:40:49 00:01     [pytest]
23:40:49 00:01       [run]
...
============== test session starts ===============
                     platform linux3 -- Python 2.6.8 -- py-1.4.20 -- pytest-2.5.2
                     plugins: timeout
                     collected 293 items

                     tests/python/pants_test/base/test_double_dag.py ....
...
                     tests/python/pants_test/tasks/test_listtargets.py .......Coverage.py warning: Module pants_test.cache was never imported.
                     Coverage.py warning: Module example_test.hello.greet was never imported.
                     Coverage.py warning: Module pants_test.commands was never imported.
                     Coverage.py warning: Module pants_test.targets was never imported.
                     ..
                      coverage: platform linux3, python 2.6.8-final-0 -
                     Name                                                                    Stmts   Miss Branch BrMiss  Cover
                     ---------------------------------------------------------------------------------------------------------
                     tests/python/pants_test/__init__                                            0      0      0      0   100%
                     tests/python/pants_test/authentication/__init__                             0      0      0      0   100%
                     tests/python/pants_test/authentication/test_netrc_util                     40      2      6      2    91%
...
                     tests/python/pants_test/testutils/mock_logger                              14      0     12      3    88%
                     ---------------------------------------------------------------------------------------------------------
                     TOTAL                                                                    3943    264    323     86    92%
                     Coverage HTML written to dir /home/jsirois/dev/3rdparty/jsirois-pantsbuild-pants/dist/coverage/3bb346293fe9bb96c6f9d6f49e2a992d024617a1

                     ===== 292 passed, 1 xfailed in 27.19 seconds =====

23:42:01 01:13     [junit]
23:42:01 01:13     [specs]
               SUCCESS

Bugs closed: 230

Reviewed at https://rbcommons.com/s/twitter/r/532/