Upgrade to Pex 1.6.10.
This pulls in a fix for the pexes Pants generates when run under CPython
3.7+ and namespace packages are involved.

See: https://github.com/pantsbuild/pex/issues/756

Before the fix both our own tool pexes and pexes we generated for end
users could fail like so:
```
$ ./pants --python-setup-interpreter-constraints="['CPython==3.7.*']" \
  test.pytest \
  --cache-ignore \
  tests/python/pants_test/backend/graph_info/tasks:cloc
...
17:16:00 00:26   [test]
...
17:16:00 00:26     [pytest]
                   Invalidated 1 target.
                   scrubbed PYTHONPATH=/home/jsirois/dev/pantsbuild/pants/src/python: from pytest environment
17:16:00 00:26       [run]
                     Traceback (most recent call last):
...
                       File "/home/jsirois/dev/pantsbuild/pants/.pants.d/test/pytest-prep/CPython-3.7.4/e307788111116c190fe04c233d334b12cdc63f77/.bootstrap/pex/pex.py", line 179, in minimum_sys_modules
                         if cls._tainted_path(module_file, site_libs):
                       File "/home/jsirois/dev/pantsbuild/pants/.pants.d/test/pytest-prep/CPython-3.7.4/e307788111116c190fe04c233d334b12cdc63f77/.bootstrap/pex/pex.py", line 157, in _tainted_path
                         paths = frozenset([path, os.path.realpath(path)])
                       File "/home/jsirois/dev/pantsbuild/jsirois-pants/build-support/pants_dev_deps.py37.venv/lib/python3.7/posixpath.py", line 394, in realpath
                         filename = os.fspath(filename)
                     TypeError: expected str, bytes or os.PathLike object, not NoneType
...
```